language: node_js
node_js:
- '8'
services:
- postgresql
- redis-server
before_install:
- npm install -g npm@6
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
- psql -c 'create database strontium;' -U postgres
script:
- npm run lint
- npm run build
- npm run test
after_script:
- npm run report-coverage
- greenkeeper-lockfile-upload
deploy:
  provider: npm
  email: alexanderchristie@outlook.com
  api_key:
    secure: cW44aOgF4LiL0bcsCeNGevzoi9ob21OodPyn3IZqba0IJ6MV0mMA1eFPwYJEV3i/APyBSmuaybQwJK3KqRl9/6OvoRTWQOXCLSmx1dFIb+3k0YsZWz3kP8POHL1xiyJoRutzNHHfNM7tu02jD1NK9B65TeY9DGItbtOrcgLCcqW90QzJZCgJzdb4j36hg+ugc411PMEZ4/DI+H0uBv+yLZTW3yzViWxBFSE+PSri0HXR/KBwonv+ljzZDJxwA05h7BSjVRerNlsnry0ZuQyZI+9mmfYO19BgN15gHaVJp8F7AM62PuF2Osgz/B/uyU/gde9j7C5LOFHe0mWqG1Jq6ynHK1ANPA/INdmwwQKLMY2RytM4QWtd3uPi2jp6wVEq2rnH17aM79u+NQmSAcYJz0jTc+aLUDxUN6d/PhCYKCS4zw2f6km+LIoJghzGsIYQ4aMqZ9spYxfmOHj3TLYYgF2jTjj1uxXPf8AfgJN6n0tchxDvy72n7ECBbnGuBQowENpQA555eJJCbWB1AXCXIs8lQ38nR9I1AnYSk4yev0NsCj/5iUX3X4o462rtW6d27lfs86B8I0wiCBUgMFTth38k9rwhvhWgXOsKwCSxOO07KGD/xBEO2cQsZM0XdYLHzLmI/mJ0ltqpWC+xtUSJvEHB4uH8c7fm09lraZ6emlg=
  skip_cleanup: true
  on:
    branch: master
env:
  global:
    secure: fQnkfv2KLHZ2zhXrX6C/s4Czr1/hvzw7z3zi3Z3N1p1c8AJ2V6YUSrhwKlZnWMn9P1S7AHGuNIn/tACmSZbg5Uwo7CyXJl7qqbhpv7lg/Vn/w+ahJF/bvwKhkj7hPSZJY3CGKft3lp44lMhejMEtgzv3t7yfPIU/Zh9dHgLhbwXRR28KUfwo8FrBbVqi7S5sdyVWy2o9G2l54ncwhp76tL4gIx//B80oAzJy/os/ls2PeyTb4IP9/CYWRbG1ESq2B+mkUqyJbCYaxvH9bJSIZ8mi0iPCV3Q43g0pBxaRscjCQ75RfjhEIiH7FaFGLilXi1xgbPtz/RN/CTCRUZNZ1qcsPRjhzPecEqV/MIU6NXwUlMzzANWMYV9qhwRkKHa4SmzdmK6nhbk3pyxkMveYZKxa084OPWRI9NyERpZ8RlzXYIqge9AyB8SswicnU3Oa3T6hnMTGxV1T9BRoCjtuxmeKaTYtsi45/dZ8llJr1JXWZsyXYsboFuDzBZl15RXCwO/A1Udzks3O2HH2yFz71iWjSvmUL7t3FeruPsTW46/PpxSLH/a8Itfo4WC4MQsXHEzjHuP4D0gK9d+cpe5hipNSuiRJyCCsoPskCjaqbfKBDf7D7+VXEP6QGhbQGcdeLX/3Ta3CAmWkVJw6xxAjv1lKThKI7AVRDgxR4+X+Q4g=
